{% set name = "pyhyperscattering" %}
{% set version = "0.2.10" %}
{% set python_min = "3.9" %}

#######################################################################
#  Placeholder root – never uploaded
#######################################################################
package:
  name: {{ name }}-suite          # dummy, avoids clashes with outputs
  version: {{ version }}

extra:
  feedstock-name: {{ name }}      # <-- important for conda-smithy bots

#######################################################################
#  Single source section for all outputs
#######################################################################
source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 99fe317f8e24204a125fc281b7eb9602959b323d5d4cfc5ad4d3aa3505c74523

#######################################################################
#  OUTPUTS
#######################################################################
outputs:

########################################################################
#  1) Core build: pyhyperscattering-base
########################################################################
  - name: {{ name }}-base
    build:
      noarch: python
      number: 0
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - wheel
        - versioneer
      run:
        - python >= {{ python_min }}
        - h5py
        - numpy
        - pandas
        - pyfai
        - scikit-image
        - scipy
        - pillow
        - xarray
        - bottleneck
        - tqdm
        - astropy-base
        - fabio
        - pydata-sphinx-theme
        - numexpr !=2.8.5,!=2.8.6
    run_exports:
      # keep downstream ABI-compatible on minor bump
      - {{ pin_subpackage(name + "-base", max_pin="x.x") }}
    test:
      imports:
        - PyHyperScattering
      commands:
        - python - <<'PY'
import importlib, sys
importlib.import_module("PyHyperScattering")
print("import OK")
PY

########################################################################
#  2) Convenience “all-nogpu” bundle: pyhyperscattering
########################################################################
  - name: {{ name }}
    build:
      noarch: generic
      script: "{{ PYTHON }} -c 'import sys; sys.exit(0)'"
    requirements:
      run:
        - {{ pin_subpackage(name + "-base", exact=True) }}
        # ---- extras: all-nogpu ----
        - tiled >=0.1.0a74
        - bluesky-tiled-plugins
        - pyopencl
        - dask
        - holoviews
        - hvplot
        - sphinx
        - pydata-sphinx-theme
        - pytest
        - black
        - codecov
        - pylint
        - flake8
        - coverage
        - pybind11
        - wheel
    test:
      imports:
        - PyHyperScattering

########################################################################
#  3) GPU bundle: pyhyperscattering-gpu  (all-nogpu + GPU bits)
########################################################################
  - name: {{ name }}-gpu
    build:
      noarch: generic
      script: "{{ PYTHON }} -c 'import sys; sys.exit(0)'"
    requirements:
      run:
        - {{ pin_subpackage(name + "-base", exact=True) }}
        # ---- extras shared with all-nogpu ----
        - tiled >=0.1.0a74
        - bluesky-tiled-plugins
        - pyopencl
        - dask
        - holoviews
        - hvplot
        - sphinx
        - pydata-sphinx-theme
        - pytest
        - black
        - codecov
        - pylint
        - flake8
        - coverage
        - pybind11
        - wheel
        # ---- GPU-only additions ----
        - cupy
        - cudatoolkit             # virtual package resolved at install time
    test:
      imports:
        - PyHyperScattering

#######################################################################
#  Meta information (shared)
#######################################################################
about:
  summary: Utilities for loading, reducing, fitting, and plotting hyperspectral x-ray and neutron scattering data.
  license: NIST-PD-fallback
  home: https://github.com/usnistgov/PyHyperScattering

extra:
  recipe-maintainers:
    - pbeaucage
