{% set name = "pyhyperscattering" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyhyperscattering-{{ version }}.tar.gz
  sha256: 3fb4c91d6d131955d0b718a02b6292e43dcdc73c7edf420b3b9931ed257cb337

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - versioneer
    - pip
  run:
    - python >={{ python_min }}
    - h5py
    - numpy <2
    - pandas
    - pyfai
    - pyopencl
    - scikit-image
    - scipy
    - pillow
    - xarray
    - tqdm
    - astropy
    - fabio
    - nodejs
    - pydata-sphinx-theme
    - numexpr !=2.8.5,!=2.8.6
    - pygix

test:
  requires:
    - python {{ python_min }}
  imports:
    - PyHyperScattering

about:
  summary: Utilities for loading, reducing, fitting, and plotting hyperspectral x-ray and neutron scattering data.
  license: NIST-PD
  license_file: LICENSE
  home: https://www.github.com/usnistgov/PyHyperScattering

extra:
  recipe-maintainers:
    - pbeaucage
